// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://egcxdjwblnylkrttfcjq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVnY3hkandibG55bGtydHRmY2pxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3ODY1NTIsImV4cCI6MjA1NzM2MjU1Mn0.XM-M-iVwxz8kAUBVUhN-ghqRmGAi0MPXuVTOlAeWm6s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);